[ERROR] Neither dataset nor target path(s) provided [get.py:__call__:835] (InsufficientArgumentsError) 
usage: datalad get [-h] [-s LABEL] [-d PATH] [-r] [-R LEVELS] [-n] [-D DESCRIPTION] [--reckless [auto|ephemeral|shared-...]]
                   [-J NJOBS]
                   [PATH [PATH ...]]
